name: Build and publish library packages on push to master

on:
  push:
    branches:
      - master
    paths-ignore:
      - .github/workflows/**

jobs:
  build-and-publish-on-master:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile and test
        uses: navikt/pb-common-gh-actions/build@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish packages
        run: gradlew publish
        env:
          GITHIB_TOKEN: ${{ secrets.GITHUB_TOKEN }}